language: R
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel
env:
  - PKG_REPOS="http://wush978.github.io/R"

before_install:
  - echo "options(repos = c('CRAN' = Sys.getenv('PKG_REPOS')))" > ~/.Rprofile

script:
  - R CMD INSTALL .
  - git clone https://github.com/wush978/DataScienceAndR.git -b course /tmp/course
  - cd /tmp/course && Rscript .test_course.R push

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - libxml2-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8552957f2dea4217e0ed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  